# Generated by Django 5.0.7 on 2024-07-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_text_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
