world = ["India", "Japan", "Hawaii", "New Zealand", "Wano"]
print(world)
print("Here is the sorted list: ")
print(sorted(world))
print("Here is the original list:")
print(world)
print("Here is the reversed list:")
world.reverse()
print(world)
print("Here is the original list:")
world.reverse()
print(world)
print("Here is the saved sorted list:")
world = sorted(world)
print(world)
