names = ["George Washington", "Monkey D Luffy", "Darth Vader", "King Arthur"]
print("Welcome " + names[0] + " to dinner.")
print("Welcome " + names[1] + " to dinner.")
print("Unfortunately" + names[2] + " will make it to dinner.")
print("So we invited " + names[3] + " instead.")
print("Oh?!\n There is a bigger table!")
names.append("Aragorn, Son of Arathorn")
print("Welcome " + names[0] + " to dinner.")
print("Welcome " + names[1] + " to dinner.")
print("Fortunately" + names[2] + " can't make it to dinner.")
print("So we invited " + names[3] + " instead.")
print("The final seat was reserved for the mighty " + names[4])
