# Generated by Django 5.0.6 on 2024-06-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='topic',
            new_name='pizza',
        ),
    ]
